### ISSUE TITLE
CocoaPods Support isn't loading plugins

### ISSUE THREAD

**Issue by orta** [RubyNative/CocoaScript#18]
``` shell
$  diamond myscript.swift

Diamond: Fetching missing pods:

platform :osx, '10.10'
plugin 'cocoapods-rome'
pod 'Alamofire'

---------------------------------------------
Error loading the plugin with path `/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-deintegrate-0.2.1/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- pod/command/deintegrate
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-deintegrate-0.2.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------


---------------------------------------------
Error loading the plugin with path `/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-dependencies-0.4.0/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- pod/command/dependencies
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-dependencies-0.4.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------


---------------------------------------------
Error loading the plugin with path `/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.5.2/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- keyring
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.5.2/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------


---------------------------------------------
Error loading the plugin with path `/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-open-0.0.8/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- pod/command/open
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-open-0.0.8/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------


---------------------------------------------
Error loading the plugin with path `/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-rome-0.3.0/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- cocoapods-rome/post_install
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-rome-0.3.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-rome` be installed. Please install it and try installation again.
*** Diamond: Could not build pods
diamond: /Users/orta/Library/Diamond/Resources/prepare.rb "/Users/orta/Library/Diamond" "myscript.swift" "myscript" "/Users/orta/Library/Diamond/Projects/myscript" "" "--verbose" returns error 1
```

**Comment by orta** [comment]
This is _totally_ my fault, I updated rubygems last night and this was the first time since then that I ran it.
